spring.application.name=netbanking-api

#DataSourceConfiguration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##premsai
spring.datasource.password=prem123
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

#JpaPropertiesConfiguration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#ServerConfiguration
server.port=9999
server.servlet.context-path=/premit

#DevToolsConfiguration
spring.devtools.restart.enabled=true